DROP TABLE IF EXISTS pokeTasks CASCADE;
DROP TABLE IF EXISTS pokeList CASCADE;


create table pokeList (

	pokeListId integer generated by default as identity,
	pokeList varchar(50) Not null,
	pokeTasks integer,
	primary key (pokeListId)
    );
	

create table pokeTasks (
	taskId integer generated by default as identity,
	pokeList varchar(50) not null, 
	pokeTask varchar(255) not null,
	pokeTaskDescription varchar(255) not null,
	difficulty integer not null,#
    date varchar(10),
    completedTickBox boolean,
    fk_pokelist_id integer NOT NULL,
	primary key (TaskId),
	foreign key (fk_pokelist_id) references pokeList(pokeListId)
);


